# Generated by Django 4.1.2 on 2023-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliverystatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shiping in progress', 'Shipping in progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
