# Generated by Django 4.1.2 on 2023-06-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('order_tno', models.CharField(max_length=150)),
                ('brand_tno', models.CharField(max_length=150)),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_logo', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('brandstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
