# Generated by Django 4.1.2 on 2023-03-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="tracking_no",
        ),
    ]
