# Generated by Django 4.1.2 on 2023-06-10 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply', '0002_alter_supplytender_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplytender',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needs_supply', to=settings.AUTH_USER_MODEL, verbose_name='supplier'),
        ),
    ]
