# Generated by Django 4.1.2 on 2023-03-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_productsupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupply',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
