# Generated by Django 4.1.2 on 2023-04-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_types', models.CharField(choices=[('DR', 'Driver'), ('FM', 'Finance Manager'), ('SM', 'Inventory Manager'), ('RD', 'Supplier'), ('CM', 'Customer'), ('MN', 'Manager'), ('BR', 'Brander'), ('DM', 'Dispatch Manager')], default='CM', max_length=3, verbose_name='question Type')),
                ('subject', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
