# Generated by Django 4.1.2 on 2023-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pg', 'Pending'), ('dc', 'Decline'), ('ap', 'Approved'), ('pr', 'Processing')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
