# Generated by Django 4.1.2 on 2023-06-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(auto_now_add=True, verbose_name='shipped_date')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered'), ('CL', 'Complete')], default='PD', max_length=3, verbose_name='status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_driver', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_service_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
