# Generated by Django 4.1.2 on 2023-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupstation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pickupstation',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userpickupstation',
            name='station',
        ),
        migrations.RemoveField(
            model_name='userpickupstation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='station',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered'), ('CL', 'Complete')], default='PD', max_length=3, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PickUpStation',
        ),
        migrations.DeleteModel(
            name='UserPickUpStation',
        ),
    ]
