# Generated by Django 4.1.2 on 2023-04-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_pickupstation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered'), ('CL', 'Complete')], default='PD', max_length=3, verbose_name='status'),
        ),
    ]
