# Generated by Django 4.1.2 on 2023-06-05 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_remove_order_county_remove_order_phone_number_and_more'),
        ('shipping', '0003_userlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='CustomerLocation',
        ),
    ]
