# Generated by Django 4.1.7 on 2023-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Out for shipping', 'Out for shipping'), ('Completed', 'completed')], default='Pending', max_length=50),
        ),
    ]
