# Generated by Django 4.1.2 on 2023-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_mode',
            new_name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=250),
        ),
    ]
