# Generated by Django 4.1.2 on 2023-02-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_mode_order_mpesa_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='amount_paid',
        ),
    ]
