# Generated by Django 4.1.7 on 2023-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Out for shipping', 'Out for shipping'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
