# Generated by Django 4.1.2 on 2023-06-02 07:59

from django.db import migrations
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_county_order_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=orders.models.CustomPhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
