# Generated by Django 4.1.2 on 2023-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
