# Generated by Django 4.1.2 on 2023-06-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town',
        ),
    ]
